on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.4
    steps:
      - name: Build ESP-IDF Project
        uses: hfudev/build-esp-idf-projects-action@master
