name: "Build Examples"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.4
    steps:
      - uses: hfudev/build-esp-idf-projects-action@master
        with:
          paths: examples
