name: "Build Examples"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.4
    strategy:
      matrix:
        parallel_index: [1, 2, 3]
        parallel_count: [3]
    steps:
      - uses: hfudev/build-esp-idf-projects-action@master
        with:
          paths: examples
          parallel_index: ${{ matrix.parallel_index }}
          parallel_count: ${{ matrix.parallel_count }}
